/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import dao.ImpressoraDAO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import model.Impressora;
import model.Manutencao;
import model.Setor;

/**
 *
 * @author renahn.sebem
 */
public class CadastroManutencaoJD extends javax.swing.JDialog {

    ImpressoraDAO daoImpressora;
    private Manutencao manutencao;
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

    public CadastroManutencaoJD(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        daoImpressora = new ImpressoraDAO();

        loadSetor(); 
        loadImpressora();

        txtData.setText(LocalDateTime.now().format(formatter));

        dao.Util.habilitarAutocomplete(cmbImpressora);

        cmbImpressora.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                preencherSetorAutomaticamente();
            }
        });
    }

    private void preencherSetorAutomaticamente() {
        Object item = cmbImpressora.getSelectedItem();
        if (item instanceof Impressora) {
            Impressora imp = (Impressora) item;
            if (imp.getAlocacao() != null) {
                cmbSetor.setSelectedItem(imp.getAlocacao().getSetor());
            } else {
                cmbSetor.setSelectedIndex(-1); // Limpa se não tiver setor
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtProblema = new javax.swing.JTextField();
        txtData = new javax.swing.JTextField();
        cmbImpressora = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cmbSetor = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Cadastro Manutenção");

        jLabel2.setText("Impressora: ");

        jLabel3.setText("Data:");

        jLabel4.setText("Problema:");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel5.setText("Setor: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtProblema))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbImpressora, 0, 223, Short.MAX_VALUE)
                                    .addComponent(txtData)
                                    .addComponent(cmbSetor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbImpressora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtProblema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalvar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (manutencao == null) {
            manutencao = new Manutencao();
        }

        try {

            Object selImpressora = cmbImpressora.getSelectedItem();
            Impressora impressoraFinal = null;

            if (selImpressora == null) {
                JOptionPane.showMessageDialog(this, "Selecione uma Impressora!");
                return;
            }

            if (selImpressora instanceof Impressora) {
                impressoraFinal = (Impressora) selImpressora;
            } else {
                String textImp = selImpressora.toString();
                for (int i = 0; i < cmbImpressora.getItemCount(); i++) {
                    Object item = cmbImpressora.getItemAt(i);
                    if (item instanceof Impressora) {
                        if (item.toString().equalsIgnoreCase(textImp)) {
                            impressoraFinal = (Impressora) item;
                            break;
                        }
                    }
                }
            }

            if (impressoraFinal == null) {
                JOptionPane.showMessageDialog(this, "Impressora inválida ou não encontrada na lista!");
                return;
            }


            manutencao.setImpressora(impressoraFinal); 

            if (cmbSetor.getSelectedItem() != null) {
                manutencao.setSetor((Setor) cmbSetor.getSelectedItem());
            }


            impressoraFinal.setDisponivel(false);

            if (txtData.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "O campo Data é obrigatório!");
                return;
            }

            java.time.LocalDate data = java.time.LocalDate.parse(txtData.getText(), formatter);
            manutencao.setDataManutencao(data);
            manutencao.setProblema(txtProblema.getText());

            this.dispose();

        } catch (java.time.format.DateTimeParseException de) {
            JOptionPane.showMessageDialog(this, "Data inválida! Use o formato dia/mês/ano (ex: 25/12/2023).");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
            this.dispose();    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroManutencaoJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroManutencaoJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroManutencaoJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroManutencaoJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroManutencaoJD dialog = new CadastroManutencaoJD(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void loadImpressora() {
        cmbImpressora.removeAllItems();
        for (Impressora obj : daoImpressora.listaImpressora()) {
            cmbImpressora.addItem(obj);
        }
        cmbImpressora.setSelectedIndex(-1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<Object> cmbImpressora;
    private javax.swing.JComboBox<Object> cmbSetor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtProblema;
    // End of variables declaration//GEN-END:variables
    public void loadSetor() {
        cmbSetor.removeAllItems();
        for (Setor obj : Setor.values()) {
            cmbSetor.addItem(obj);
        }
        cmbSetor.setSelectedIndex(-1);
    }

    public Manutencao getManutencao() {
        return manutencao;
    }

    public void setManutencao(Manutencao manutencao) {
        this.manutencao = manutencao;

        // Preenche a Impressora (Lógica do Serial Number)
        Impressora impAlocada = manutencao.getImpressora();

        if (impAlocada != null) {
            for (int i = 0; i < cmbImpressora.getItemCount(); i++) {
                Object item = cmbImpressora.getItemAt(i);

                if (item instanceof Impressora) {
                    Impressora impCombo = (Impressora) item;

                    if (impCombo.getSerialNumber().equals(impAlocada.getSerialNumber())) {
                        cmbImpressora.setSelectedIndex(i);
                        break;
                    }
                }
            }
        }

        if (manutencao.getDataManutencao() != null) {
            txtData.setText(manutencao.getDataManutencao().format(formatter));
        } else {
            txtData.setText("");
        }

        txtProblema.setText(manutencao.getProblema());
    }
}
