package view;

import dao.ManutencaoDAO;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Impressora;
import model.Manutencao;

/**
 *
 * @author renahn.sebem
 */
public class ListaManutencaoJF extends javax.swing.JFrame {

    /**
     * Creates new form ListaManutencaoJF
     */
    ManutencaoDAO dao;
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

    public ListaManutencaoJF() {
        initComponents();
        dao = new ManutencaoDAO();
        configurarTabela();
        loadTabelaManutencao();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblManutencao = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btnInfo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblManutencao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Impressora", "Serial Number", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblManutencao);

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        btnInfo.setText("Mais Informacões");
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRemover)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInfo)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnEditar)
                    .addComponent(btnRemover)
                    .addComponent(btnInfo))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void configurarTabela() {
var colunaModelo = tblManutencao.getColumnModel().getColumn(0);

        colunaModelo.setCellRenderer(new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {

                super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                if (value instanceof Manutencao) {
                    Manutencao manu = (Manutencao) value;
                    
                    if (manu.getImpressora() != null && manu.getImpressora().getModelo() != null) {
                        setText(manu.getImpressora().getModelo().getDescricao());
                    } else {

                        String hist = manu.getHistoricoModelo();
                        setText((hist != null ? hist : "Desconhecida") + " (Excluída)");
                    }
                }
                return this;
            }
        });
    }
    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        CadastroManutencaoJD telaCadastro = new CadastroManutencaoJD(this, rootPaneCheckingEnabled);
        telaCadastro.setVisible(true);

        Manutencao novo = telaCadastro.getManutencao();

        if (novo != null) {
            try {
                dao.persist(novo);
                loadTabelaManutencao();
            } catch (Exception ex) {
                System.err.println("Erro ao adicionar Manutenção: " + ex);
                JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (tblManutencao.getSelectedRow() != -1) {
            Manutencao objSelecionado = (Manutencao) tblManutencao.getValueAt(tblManutencao.getSelectedRow(), 0);

            CadastroManutencaoJD telaEdicao = new CadastroManutencaoJD(this, true);
            telaEdicao.setManutencao(objSelecionado); // Passa os dados
            telaEdicao.setVisible(true);

            Manutencao objRetorno = telaEdicao.getManutencao();

            if (objRetorno != null) {
                try {
                    dao.persist(objRetorno);
                    loadTabelaManutencao();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Erro ao editar: " + ex.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione uma manutenção para editar.");
        }    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
if (tblManutencao.getSelectedRow() != -1) {
            Manutencao obj = (Manutencao) tblManutencao.getModel().getValueAt(tblManutencao.getSelectedRow(), 0);
            
            String desc = (obj.getImpressora() != null) 
                    ? obj.getImpressora().getModelo().getDescricao() 
                    : obj.getHistoricoModelo() + " (Excluída)";
            
            int op_remover = JOptionPane.showConfirmDialog(rootPane, "Tem certeza que deseja remover o registro de manutenção de:\n" + desc + "?");
            
            if (op_remover == JOptionPane.YES_OPTION) {
                try {
                    dao.remover(obj);
                    loadTabelaManutencao();
                    JOptionPane.showMessageDialog(rootPane, "Registro removido com sucesso!");
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(rootPane, "Erro ao remover: " + ex.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione uma linha");
        
        }    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
if (tblManutencao.getSelectedRow() != -1) {
            Manutencao obj = (Manutencao) tblManutencao.getModel().getValueAt(tblManutencao.getSelectedRow(), 0);
            JOptionPane.showMessageDialog(rootPane, obj.exibirDados());
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione uma linha");
        
        }    }//GEN-LAST:event_btnInfoActionPerformed

    public void loadTabelaManutencao() {
DefaultTableModel modelo = (DefaultTableModel) tblManutencao.getModel();
        modelo.setNumRows(0);

        for (Manutencao obj : dao.listaManutencao()) {
            
            String dataFmt = "";
            if(obj.getDataManutencao() != null){
                dataFmt = obj.getDataManutencao().format(formatter);
            }

           
            String snMostrar = (obj.getImpressora() != null) 
                    ? obj.getImpressora().getSerialNumber() 
                    : obj.getHistoricoSN();

            Object[] linha = {
                obj,        
                snMostrar,  
                dataFmt     
            };
            modelo.addRow(linha);
        }
    }
    

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaManutencaoJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaManutencaoJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaManutencaoJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaManutencaoJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaManutencaoJF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnRemover;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblManutencao;
    // End of variables declaration//GEN-END:variables
}
